version: '3'
services:
  mysql:
    container_name: sica-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: esp
      MYSQL_DATABASE: sica
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql