spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sica
    username: root
    password: esp
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/sica
    user: root
    password: esp
    baseline-on-migrate: true
    locations: classpath:db/migration/prod
