spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sica}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:esp}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    repair: true
    locations: classpath:db/migration/prod
